// `agentready fix` — turn audit findings into starter files. Strictly additive:
// a fixer may only propose files that do not exist yet, and apply never
// overwrites. Content gaps inside existing files (a thin CLAUDE.md, a README
// missing sections) stay manual — generating prose into someone's files is a
// judgment call, creating a clearly-marked stub where there was nothing is not.
// Every stub is honest: detected facts are real, everything else is a TODO.

import fs from 'node:fs';
import path from 'node:path';
import { createContext, README_PATTERN, CONTRIBUTING_PATTERN } from './context.js';
import { findTestCommand } from './checks/test-runnability.js';
import { ENV_PINS } from './checks/setup-reproducibility.js';
import { findInstructionFiles } from './checks/instruction-files.js';

const CI_CONFIGS = [
  '.gitlab-ci.yml', '.circleci/config.yml', 'Jenkinsfile', 'azure-pipelines.yml',
  '.travis.yml', 'bitbucket-pipelines.yml', '.drone.yml', '.woodpecker.yml',
  '.buildkite/pipeline.yml',
];

/**
 * Inspect the repo at `root` and return the list of files `fix` would create:
 * [{ checkId, path, reason, content }]. Pure planning — nothing is written.
 */
export function planFixes(root) {
  const ctx = createContext(root);
  const eco = detectEcosystem(ctx);
  const testCommand = findTestCommand(ctx);
  const plan = [];

  if (findInstructionFiles(ctx).length === 0) {
    plan.push({
      checkId: 'agent-instructions',
      path: 'AGENTS.md',
      reason: 'no agent instructions file',
      content: agentsStub(ctx, eco, testCommand),
    });
  }

  if (!ctx.findRootFile(README_PATTERN)) {
    plan.push({
      checkId: 'docs-structure',
      path: 'README.md',
      reason: 'no README',
      content: readmeStub(ctx),
    });
  }

  const readmeName = ctx.findRootFile(README_PATTERN);
  const readme = readmeName ? ctx.read(readmeName) ?? '' : '';
  if (!ctx.findRootFile(CONTRIBUTING_PATTERN) && !/contribut/i.test(readme)) {
    plan.push({
      checkId: 'docs-structure',
      path: 'CONTRIBUTING.md',
      reason: 'no contributor docs',
      content: contributingStub(testCommand),
    });
  }

  if (!ctx.exists('.gitignore')) {
    plan.push({
      checkId: 'repo-hygiene',
      path: '.gitignore',
      reason: 'no .gitignore',
      content: gitignoreStub(eco),
    });
  }

  if (eco === 'node' && hasNodeLockfile(ctx) && !ENV_PINS.some((f) => ctx.exists(f))) {
    plan.push({
      checkId: 'setup-reproducibility',
      path: '.nvmrc',
      reason: 'lockfile committed but runtime version not pinned',
      content: `${process.version.match(/^v(\d+)/)[1]}\n`,
    });
  }

  const hasCi = ctx.files().some((f) => f.startsWith('.github/workflows/') && /\.ya?ml$/.test(f))
    || CI_CONFIGS.some((f) => ctx.exists(f));
  if (!hasCi) {
    const workflow = ciStub(ctx, eco, testCommand);
    if (workflow) {
      plan.push({
        checkId: 'ci-config',
        path: '.github/workflows/test.yml',
        reason: 'no CI configuration',
        content: workflow,
      });
    }
  }

  return plan;
}

/**
 * Write the planned files. Re-checks existence at write time and never
 * overwrites — returns { created, skipped } of repo-relative paths.
 */
export function applyFixes(root, plan) {
  const created = [];
  const skipped = [];
  for (const item of plan) {
    const full = path.join(root, item.path);
    if (fs.existsSync(full)) {
      skipped.push(item.path);
      continue;
    }
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, item.content);
    created.push(item.path);
  }
  return { created, skipped };
}

function detectEcosystem(ctx) {
  if (ctx.exists('package.json')) return 'node';
  if (ctx.exists('pyproject.toml') || ctx.exists('setup.py') || ctx.exists('Pipfile')
    || ctx.exists('requirements.txt')) return 'python';
  if (ctx.exists('Cargo.toml')) return 'rust';
  if (ctx.exists('go.mod')) return 'go';
  return null;
}

function hasNodeLockfile(ctx) {
  return ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb', 'bun.lock']
    .some((f) => ctx.exists(f));
}

function projectName(ctx) {
  return ctx.readJson('package.json')?.name ?? path.basename(ctx.root);
}

function setupCommand(ctx, eco) {
  if (eco === 'node') return hasNodeLockfile(ctx) ? 'npm ci' : 'npm install';
  if (eco === 'python') return ctx.exists('requirements.txt') ? 'pip install -r requirements.txt' : 'pip install -e .';
  if (eco === 'rust') return 'cargo build';
  if (eco === 'go') return 'go build ./...';
  return null;
}

function topLevelDirs(ctx) {
  const dirs = new Set();
  for (const f of ctx.files()) {
    const slash = f.indexOf('/');
    if (slash > 0) dirs.add(f.slice(0, slash));
  }
  return [...dirs].sort();
}

function agentsStub(ctx, eco, testCommand) {
  const setup = setupCommand(ctx, eco);
  const dirs = topLevelDirs(ctx);
  return `# Agent instructions

<!-- Generated by \`agentready fix\`. Detected commands below are real; fill in
     every TODO — agents follow this file literally, so wrong or missing
     instructions send them down dead ends. -->

## Project

\`${projectName(ctx)}\` — TODO: one sentence on what this project does.

## Setup

${setup ? `\`\`\`\n${setup}\n\`\`\`` : 'TODO: the commands that take a fresh clone to a working dev environment.'}

## Tests

${testCommand
    ? `Run the suite before pushing:\n\n\`\`\`\n${testCommand}\n\`\`\``
    : 'TODO: how to run the tests. If there is no suite yet, say so explicitly.'}

## Project structure

${dirs.length
    ? dirs.map((d) => `- \`${d}/\` — TODO: what lives here`).join('\n')
    : 'TODO: describe the directory layout.'}

## Conventions

TODO: code style, naming, patterns to follow, and anything an agent must never do.
`;
}

function readmeStub(ctx) {
  return `# ${projectName(ctx)}

TODO: one paragraph — what this project is and why someone would use it.

<!-- Generated by \`agentready fix\` — replace every TODO. -->

## Install

\`\`\`
TODO: installation command
\`\`\`

## Usage

\`\`\`
TODO: minimal working example
\`\`\`
`;
}

function contributingStub(testCommand) {
  return `# Contributing

<!-- Generated by \`agentready fix\` — adjust to how this project actually works. -->

TODO: how to file issues and propose changes (fork + PR? issue first?).

## Development

${testCommand
    ? `Run the test suite before submitting:\n\n\`\`\`\n${testCommand}\n\`\`\``
    : 'TODO: dev setup and how to verify changes.'}
`;
}

function gitignoreStub(eco) {
  const generic = ['# Generated by `agentready fix` — extend for your toolchain.', '.env', '*.log'];
  const byEco = {
    node: ['node_modules/', 'dist/', 'coverage/'],
    python: ['__pycache__/', '*.pyc', '.venv/', 'venv/', 'dist/', 'build/', '*.egg-info/'],
    rust: ['target/'],
    go: ['bin/'],
  };
  return [...generic, ...(byEco[eco] ?? [])].join('\n') + '\n';
}

// Only generated when the workflow is near-certain to run as-is: hosted
// runners ship the node/rust/go toolchains, so checkout + test just works.
// `make test`/`pytest` repos need unknowable setup — no stub beats a red one.
function ciStub(ctx, eco, testCommand) {
  if (!testCommand) return null;
  let steps;
  if (testCommand === 'npm test') {
    steps = `      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: ${hasNodeLockfile(ctx) ? 'npm ci' : 'npm install'}
      - run: npm test`;
  } else if (testCommand === 'cargo test' || testCommand === 'go test ./...') {
    steps = `      - run: ${testCommand}`;
  } else {
    return null;
  }
  return `# Generated by \`agentready fix\`.
name: test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${steps}
`;
}
